---
name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Python
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip3 install pip --upgrade
          pip3 install wheel
          pip3 install -r requirements.txt
          pip3 install pytest

      - name: Run tests
        run: ./venv/bin/pytest
